AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: User management system for SOSW masterclasses

Parameters:
  LambdaUserManagerFunctionName:
    Description: "Name of Lambda Function."
    Type: String
    Default: 'sys-user-management'

Resources:
  LambdaUserManager:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref LambdaUserManagerFunctionName
      Role: !GetAtt LambdaExecutionRole.Arn
      CodeUri: src/
      Description: Create users for SOSW masterclasses
      Handler: app.lambda_handler
      MemorySize: 256
      PackageType: Zip
      Runtime: python3.11
      Timeout: 300
      Tracing: Active

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${LambdaUserManagerFunctionName}Role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "lambda-policy-sys-user-management"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                    - "iam:*"
                    - "lambda:*"
                Resource: "*"
